[global]
   workgroup = WORKGROUP
   server string = KLM Fileserver
   netbios name = SAMBA-FS
   security = user
   map to guest = never
   unix charset = UTF-8

[mandate]
   path = /srv/samba/mandate
   valid users = @treuhand @gl
   read only = no

[buchhaltung]
   path = /srv/samba/buchhaltung
   valid users = @buchhaltung @gl
   read only = no

[personal]
   path = /srv/samba/personal
   valid users = @personal @gl
   read only = no

[vorlagen]
   path = /srv/samba/vorlagen
   valid users = @treuhand @buchhaltung @personal @gl
   read only = yes
